CB.EN.U4CSE20304
19CSE304- Assignment 1

1.	Generate a tuple from the set ["aman", "222", 777, 400.4]
2.	Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.
3.	Use rand function to generate a 2-dimensional random array with seed.
4.	Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
5.	Return a random integer N such that 20 <= N <= 90. 
6.	Given a population or set[11, 12, 13,14, 15]
o	Return a 3 length list of unique elements without replacement.
o	Shuffle the above set
o	Print a random number from the set
7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
8.	Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. 
9.	Given a string "The King is Dead, Long Live The King" 
o	Print the complete string
o	Print first character of the string
o	Print characters starting from 3rd to 5th
o	Print string starting from 3rd character
o	Split the words


In [4]:
import pandas as pd
import numpy as np

In [3]:
set=['aman', "222", 777, 400.4]
print(tuple(set))

('aman', '222', 777, 400.4)


In [4]:
dict={'Roll No': 20304 ,
      'First Name': 'Aksita',
      'Last Name': 'G',
      'DOB': 2407    
}
print(dict)

{'Roll No': 20304, 'First Name': 'Aksita', 'Last Name': 'G', 'DOB': 2407}


In [14]:
np.random.seed(0)
np.random.randint(low=0, high=10, size=(2,2))

array([[5, 0],
       [3, 3]])

In [18]:
import random
print(random.uniform(0.0, 1.0))
print(abs(-1234))

0.7734929113934618
1234


In [21]:
print(random.randint(20, 90))

39


In [28]:
list1=[11,12,12,13,14]
unique_list=[]
for x in list1:
    if x  not in unique_list:
        unique_list.append(x)
three=unique_list[0:3]
print(three)
random.shuffle(list1)
print(list1)
print(random.choice(list1))

[11, 12, 13]
[14, 12, 12, 13, 11]
13


In [29]:
import os
os.getcwd()

'C:\\Users\\aksit'

In [34]:
os.chdir(r"C:\\Users\\aksit\\Downloads")
#os.mkdir('king')
#os.chdir('king')
f=open('king.txt','w+')
f.write('The King is Dead, Long Live The King')
f.seek(0)
print(f.read())
f.close()

The King is Dead, Long Live The King


In [36]:
os.rename('king.txt', 'note.txt')
os.remove('note.txt')

In [3]:
def create():
        for letter in "DataScience":
            if letter == "e":
                break
            if letter == "a":
                continue
            print(letter)
create()

D
t
S
c
i


In [7]:
s="The King is Dead , Long Live The King"
print(s)
print(s[0])
print(s[2:5])
print(s[2:])
print(s.split(" "), sep="\n")

The King is Dead , Long Live The King
T
e K
e King is Dead , Long Live The King
['The', 'King', 'is', 'Dead', ',', 'Long', 'Live', 'The', 'King']


10.	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements
11.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).
12.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
o	Slice and display the 2nd row.
o	Write code to display as array([2., 5.]) 
o	Find the length of the array.
13.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array
14.	Create an array from a list of 1,2 and 3.
15.	Fill an array [1,2,3] with a single value [9,9,9]. 
16.	Sum the elements of array [2,4,5].
17.	Give the products of array [77,74,75]
18.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.
19.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
20.	Find dot product of two arrays [1, 2, 3]and [0, 1, 1]. 
21.	Find the eigenvalues and eigenvectors of matrix A.


In [11]:
#10
import numpy as np
mylist = [1,4,5,8]
arr = np.array(mylist)
print (arr)
print (type(arr))
print(arr[0:2])

[1 4 5 8]
<class 'numpy.ndarray'>
[1 4]


In [14]:
#11
array = np.arange(1,7).reshape(2,3)
array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#12
print(array[1:2])
#arr1=array.tolist()
print(list(array))
print(len(array))

[[4 5 6]]
[array([1, 2, 3]), array([4, 5, 6])]
2


In [71]:
#13
a = np.arange(0, 10)
print(a)
ar=a.reshape(2,5)
print(ar)
print(np.transpose(ar))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [70]:
#14
x=[12, 78, 43 ,21]
y=[56, 39, 74, 16]
z=[2, 85, 16, 90]
new=x+y+z
a=np.array(new)
a.shape=(3,4)
a

array([[12, 78, 43, 21],
       [56, 39, 74, 16],
       [ 2, 85, 16, 90]])

In [51]:
#15
arr=np.array([1,2,3])
print(arr)
arr.fill(9)
arr

[1 2 3]


array([9, 9, 9])

In [42]:
#16
arr=[2,4,5]
print(sum(arr))

11


In [40]:
#17
arr=[77,74,75]
print(np.prod(arr))

427350


In [32]:
 #18
list=[2,1,9,1,2,22,1,1,4,55,6,2,56]
print("Mean:",np.average(list))
print("Variance:",np.var(list))
print("Standard Deviation:",np.std(list))
print("Min:",np.min(list))
print("Max:",np.max(list))
print("Argmax:",np.argmax(list))
print("Argmin:",np.argmin(list))
print("Median:",np.median(list))

Mean: 12.461538461538462
Variance: 367.32544378698225
Standard Deviation: 19.165736192147232
Min: 1
Max: 56
Argmax: 12
Argmin: 1
Median: 2.0


In [23]:
#19
l1=[1, 1, 4, 5, 5, 5, 7] 
l2=[]
for x in l1:
    if(x not in l2):
        l2.append(x)
l2.sort()
l2

[1, 4, 5, 7]

In [24]:
#20
import numpy.matlib 
a = np.array([1,2,3]) 
b = np.array([0,1,1]) 
np.dot(a,b)


5

In [26]:
#21
m = np.array([[2, -12],
              [1, -5]])
w, v = np.linalg.eig(m)
print("Eigen values:", w)
print("Eigen vectors:", v)

Eigen values: [-1. -2.]
Eigen vectors: [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
